/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterfaceSwing;

import Entidades.Fazenda;
import javax.swing.JOptionPane;

/**
 *
 * @author Slipmp
 */
public class frmMain extends javax.swing.JFrame {

    private Entidades.Jogo oJogoAtivo=null;
    RegrasNegocio.JogoRegrasNegocio oJogoRegrasNegocio=new RegrasNegocio.JogoRegrasNegocio();
    RegrasNegocio.MapaRegrasNegocio oMapaRegrasNegocio=new RegrasNegocio.MapaRegrasNegocio();
    RegrasNegocio.HabitatRegrasNegocio oHabitatRegrasNegocio=new RegrasNegocio.HabitatRegrasNegocio();
    RegrasNegocio.DragaoRegrasNegocio oDragaoRegrasNegocio=new RegrasNegocio.DragaoRegrasNegocio();
    RegrasNegocio.NivelRegrasNegocio oNivelRegrasNegocio=new RegrasNegocio.NivelRegrasNegocio();
    
    private final String STR_BOTAO="btnMapaLocal";
    /**
     * Creates new form frmMain
     */
    public frmMain()  {
        initComponents();
        try
        {
            CarregarItensTela();
            CarregarEventosBotoes();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "Erro abrir a aplicação. Descrição: "+ ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDadosGerais = new javax.swing.JLabel();
        jPanelBotoes = new javax.swing.JPanel();
        btnMapaLocal1x1 = new javax.swing.JButton();
        btnMapaLocal1x2 = new javax.swing.JButton();
        btnMapaLocal1x3 = new javax.swing.JButton();
        btnMapaLocal1x4 = new javax.swing.JButton();
        btnMapaLocal1x5 = new javax.swing.JButton();
        btnMapaLocal1x6 = new javax.swing.JButton();
        btnMapaLocal2x1 = new javax.swing.JButton();
        btnMapaLocal2x2 = new javax.swing.JButton();
        btnMapaLocal2x3 = new javax.swing.JButton();
        btnMapaLocal2x4 = new javax.swing.JButton();
        btnMapaLocal2x5 = new javax.swing.JButton();
        btnMapaLocal2x6 = new javax.swing.JButton();
        btnMapaLocal3x1 = new javax.swing.JButton();
        btnMapaLocal3x2 = new javax.swing.JButton();
        btnMapaLocal3x3 = new javax.swing.JButton();
        btnMapaLocal3x4 = new javax.swing.JButton();
        btnMapaLocal3x5 = new javax.swing.JButton();
        btnMapaLocal3x6 = new javax.swing.JButton();
        btnMapaLocal4x1 = new javax.swing.JButton();
        btnMapaLocal4x2 = new javax.swing.JButton();
        btnMapaLocal4x3 = new javax.swing.JButton();
        btnMapaLocal4x4 = new javax.swing.JButton();
        btnMapaLocal4x5 = new javax.swing.JButton();
        btnMapaLocal4x6 = new javax.swing.JButton();
        btnMapaLocal5x1 = new javax.swing.JButton();
        btnMapaLocal5x2 = new javax.swing.JButton();
        btnMapaLocal5x3 = new javax.swing.JButton();
        btnMapaLocal5x4 = new javax.swing.JButton();
        btnMapaLocal5x5 = new javax.swing.JButton();
        btnMapaLocal5x6 = new javax.swing.JButton();
        jPanelOpcoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCriarJogo = new javax.swing.JButton();
        btnSairJogo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblMackDragonCity = new javax.swing.JLabel();

        setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblDadosGerais.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblDadosGerais.setText("lblDadosGerais");

        jPanelBotoes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelBotoes.setToolTipText("Mapa");

        btnMapaLocal1x1.setText("<html>MapaLocal 1x1 <br /> Nome Dragão");
        btnMapaLocal1x1.setActionCommand("");
        btnMapaLocal1x1.setName("btnMapaLocal1x1"); // NOI18N

        btnMapaLocal1x2.setText("<html>MapaLocal 1x2 <br /> Nome Dragão");
        btnMapaLocal1x2.setActionCommand("");
        btnMapaLocal1x2.setName("btnMapaLocal1x2"); // NOI18N

        btnMapaLocal1x3.setText("<html>MapaLocal 1x3  <br /> Nome Dragão");
        btnMapaLocal1x3.setActionCommand("");
        btnMapaLocal1x3.setName("btnMapaLocal1x3"); // NOI18N

        btnMapaLocal1x4.setText("<html>MapaLocal 1x4 <br /> Nome Dragão");
        btnMapaLocal1x4.setActionCommand("");
        btnMapaLocal1x4.setName("btnMapaLocal1x4"); // NOI18N

        btnMapaLocal1x5.setText("<html>MapaLocal 1x5 <br /> Nome Dragão");
        btnMapaLocal1x5.setActionCommand("");
        btnMapaLocal1x5.setName("btnMapaLocal1x5"); // NOI18N

        btnMapaLocal1x6.setText("<html>MapaLocal 1x6 <br /> Nome Dragão");
        btnMapaLocal1x6.setActionCommand("");
        btnMapaLocal1x6.setName("btnMapaLocal1x6"); // NOI18N

        btnMapaLocal2x1.setText("<html>MapaLocal 2x1 <br /> Nome Dragão");
        btnMapaLocal2x1.setActionCommand("");
        btnMapaLocal2x1.setName("btnMapaLocal2x1"); // NOI18N

        btnMapaLocal2x2.setText("<html>MapaLocal 2x2 <br /> Nome Dragão<br/>");
        btnMapaLocal2x2.setActionCommand("");
        btnMapaLocal2x2.setName("btnMapaLocal2x2"); // NOI18N

        btnMapaLocal2x3.setText("<html>MapaLocal 2x3 <br /> Nome Dragão");
        btnMapaLocal2x3.setActionCommand("");
        btnMapaLocal2x3.setName("btnMapaLocal2x3"); // NOI18N

        btnMapaLocal2x4.setText("<html>MapaLocal 2x4 <br /> Nome Dragão");
        btnMapaLocal2x4.setActionCommand("");
        btnMapaLocal2x4.setName("btnMapaLocal2x4"); // NOI18N

        btnMapaLocal2x5.setText("<html>MapaLocal 2x5 <br /> Nome Dragão");
        btnMapaLocal2x5.setActionCommand("");
        btnMapaLocal2x5.setName("btnMapaLocal2x5"); // NOI18N

        btnMapaLocal2x6.setText("<html>MapaLocal 2x6 <br /> Nome Dragão");
        btnMapaLocal2x6.setActionCommand("");
        btnMapaLocal2x6.setName("btnMapaLocal2x6"); // NOI18N

        btnMapaLocal3x1.setText("<html>MapaLocal 3x1 <br /> Nome Dragão");
        btnMapaLocal3x1.setActionCommand("");
        btnMapaLocal3x1.setName("btnMapaLocal3x1"); // NOI18N

        btnMapaLocal3x2.setText("<html>MapaLocal 3x2 <br /> Nome Dragão");
        btnMapaLocal3x2.setActionCommand("");
        btnMapaLocal3x2.setName("btnMapaLocal3x2"); // NOI18N

        btnMapaLocal3x3.setText("<html>MapaLocal 3x3 <br /> Nome Dragão");
        btnMapaLocal3x3.setActionCommand("");
        btnMapaLocal3x3.setName("btnMapaLocal3x3"); // NOI18N

        btnMapaLocal3x4.setText("<html>MapaLocal 3x4 <br /> Nome Dragão");
        btnMapaLocal3x4.setActionCommand("");
        btnMapaLocal3x4.setName("btnMapaLocal3x4"); // NOI18N

        btnMapaLocal3x5.setText("<html>MapaLocal 3x5 <br /> Nome Dragão");
        btnMapaLocal3x5.setActionCommand("");
        btnMapaLocal3x5.setName("btnMapaLocal3x5"); // NOI18N

        btnMapaLocal3x6.setText("<html>MapaLocal 3x6 <br /> Nome Dragão");
        btnMapaLocal3x6.setActionCommand("");
        btnMapaLocal3x6.setName("btnMapaLocal3x6"); // NOI18N

        btnMapaLocal4x1.setText("<html>MapaLocal 4x1 <br /> Nome Dragão");
        btnMapaLocal4x1.setActionCommand("");
        btnMapaLocal4x1.setName("btnMapaLocal4x1"); // NOI18N

        btnMapaLocal4x2.setText("<html>MapaLocal 4x2 <br /> Nome Dragão");
        btnMapaLocal4x2.setActionCommand("");
        btnMapaLocal4x2.setName("btnMapaLocal4x2"); // NOI18N

        btnMapaLocal4x3.setText("<html>MapaLocal 4x3 <br /> Nome Dragão");
        btnMapaLocal4x3.setActionCommand("");
        btnMapaLocal4x3.setName("btnMapaLocal4x3"); // NOI18N

        btnMapaLocal4x4.setText("<html>MapaLocal 4x4 <br /> Nome Dragão");
        btnMapaLocal4x4.setActionCommand("");
        btnMapaLocal4x4.setName("btnMapaLocal4x4"); // NOI18N

        btnMapaLocal4x5.setText("<html>MapaLocal 4x5 <br /> Nome Dragão");
        btnMapaLocal4x5.setActionCommand("");
        btnMapaLocal4x5.setName("btnMapaLocal4x5"); // NOI18N

        btnMapaLocal4x6.setText("<html>MapaLocal 4x6 <br /> Nome Dragão");
        btnMapaLocal4x6.setActionCommand("");
        btnMapaLocal4x6.setName("btnMapaLocal4x6"); // NOI18N

        btnMapaLocal5x1.setText("<html>MapaLocal 5x1  <br /> Nome Dragão");
        btnMapaLocal5x1.setActionCommand("");
        btnMapaLocal5x1.setName("btnMapaLocal5x1"); // NOI18N

        btnMapaLocal5x2.setText("<html>MapaLocal 5x2 <br /> Nome Dragão");
        btnMapaLocal5x2.setActionCommand("");
        btnMapaLocal5x2.setName("btnMapaLocal5x2"); // NOI18N

        btnMapaLocal5x3.setText("<html>MapaLocal 5x3  <br /> Nome Dragão");
        btnMapaLocal5x3.setActionCommand("");
        btnMapaLocal5x3.setName("btnMapaLocal5x3"); // NOI18N

        btnMapaLocal5x4.setText("<html>MapaLocal 5x4 <br /> Nome Dragão");
        btnMapaLocal5x4.setActionCommand("");
        btnMapaLocal5x4.setName("btnMapaLocal5x4"); // NOI18N

        btnMapaLocal5x5.setText("<html>MapaLocal 5x5 <br /> Nome Dragão");
        btnMapaLocal5x5.setActionCommand("");
        btnMapaLocal5x5.setName("btnMapaLocal5x5"); // NOI18N

        btnMapaLocal5x6.setText("<html>MapaLocal 5x6 <br /> Nome Dragão");
        btnMapaLocal5x6.setActionCommand("");
        btnMapaLocal5x6.setName("btnMapaLocal5x6"); // NOI18N

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMapaLocal1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMapaLocal1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMapaLocal1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMapaLocal1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMapaLocal1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMapaLocal1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBotoesLayout.createSequentialGroup()
                        .addComponent(btnMapaLocal5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBotoesLayout.createSequentialGroup()
                        .addComponent(btnMapaLocal4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBotoesLayout.createSequentialGroup()
                        .addComponent(btnMapaLocal3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBotoesLayout.createSequentialGroup()
                        .addComponent(btnMapaLocal2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMapaLocal2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMapaLocal1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMapaLocal1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMapaLocal1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMapaLocal2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMapaLocal2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMapaLocal2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMapaLocal3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMapaLocal3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMapaLocal4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMapaLocal4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMapaLocal4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMapaLocal5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMapaLocal5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMapaLocal5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMapaLocal5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMapaLocal5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelOpcoes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setText("Opções");

        btnCriarJogo.setText("Criar Novo Jogo");
        btnCriarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarJogoActionPerformed(evt);
            }
        });

        btnSairJogo.setText("Sair do Jogo");
        btnSairJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairJogoActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterfaceSwing/lblLogoMackenzie.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblMackDragonCity.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblMackDragonCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMackDragonCity.setText("<html>MackDragonCity <br />1.0  Beta");

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCriarJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSairJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMackDragonCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21))
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCriarJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSairJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMackDragonCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDadosGerais, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosGerais)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jPanelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void btnSairJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairJogoActionPerformed
        SairDoJogo();
    }//GEN-LAST:event_btnSairJogoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try 
        {   
            GravarJogo();
            System.exit(0);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao gravar jogo ao sair. Descrição: "+ ex.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCriarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarJogoActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja criar um Novo jogo?")==JOptionPane.YES_OPTION)
        {
            try {   
                CriarNovoJogo();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao Criar novo jogo. Descrição: "+ ex.getMessage());
            }
        }        
    }//GEN-LAST:event_btnCriarJogoActionPerformed

    private void GravarJogo() throws Exception
    {
        oJogoRegrasNegocio.GravarJogo(oJogoAtivo);
    }
    private void SairDoJogo()
    {
        if(JOptionPane.showConfirmDialog(rootPane, "Você tem certeza que deseja sair do jogo?")==JOptionPane.YES_OPTION)
        {
            try {   
                GravarJogo();
                System.exit(0);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao gravar jogo ao sair. Descrição: "+ ex.getMessage());
            }
        } 
    }
    private void CriarNovoJogo() throws Exception
    {
        String strNome="";
        while(strNome==null || strNome.trim().length()==0)
        {
            strNome=JOptionPane.showInputDialog("Por favor insira o nome do Jogador!");
        }
        Entidades.Jogador oJogador=new Entidades.Jogador();
        oJogador.setNome(strNome);
        
        oJogoAtivo=oJogoRegrasNegocio.CriarNovoJogo(oJogador);
        GravarJogo();
        CarregarItensTela();
    }
    
    /**
     * Esse método é uma "mini-simulação" de método recursivo! 
     */
    private void CarregarItensTela() throws Exception
    {
        if(oJogoAtivo==null)
        {
            oJogoAtivo=oJogoRegrasNegocio.LerJogo();
        }
        
        if(oJogoAtivo==null) {
            CriarNovoJogo();
        }
        else
        {
            CarregarBotoes();
            CarregarLabels();
        }
    }
    
    private void CarregarLabels()
    {
        String strDadosGerais="Nome do Jogador: %s | Total de Ouro: %s | Total de Comida: %s | Level: %s | Total de XP: %s";
        strDadosGerais=String.format(strDadosGerais, 
                oJogoAtivo.getJogador().getNome(),
                oJogoAtivo.getVlrTotalOuro(),
                oJogoAtivo.getVlrTotalComida(),
                oNivelRegrasNegocio.getNivelEquivalente(oJogoAtivo.getQtdTotalPontosXP()).getCodigo(),
                oJogoAtivo.getQtdTotalPontosXP()
                );
        lblDadosGerais.setText(strDadosGerais);
    }
    private void CarregarBotoes()
    {
        for(int x=1;x<=5;x++)
        {
            for(int y=1;y<=6;y++)
            {
                for(java.awt.Component oComponent : jPanelBotoes.getComponents())
                {
                    if(oComponent.getName().equals(STR_BOTAO+x+"x"+y))
                    {
                        Entidades.MapaLocal oMapaLocal=oMapaRegrasNegocio.getMapaLocalPorPosicao(oJogoAtivo.getMapa(), x, y);
                        javax.swing.JButton oButtonMapaLocal =(javax.swing.JButton)oComponent;
                        
                        if(oMapaLocal.getConstrucao()!=null)
                        {
                            String strTextoBotao="<html>"+oMapaLocal.getConstrucao().getNome();
                            if(oMapaLocal.getConstrucao() instanceof Entidades.CasaCentral)
                            {
                                if(((Entidades.CasaCentral)oMapaLocal.getConstrucao()).getOvo()!=null)
                                {
                                    strTextoBotao+="<br />" + ((Entidades.CasaCentral)oMapaLocal.getConstrucao()).getOvo().getNomeDragao();
                                }
                            }
                            
                            if(oMapaLocal.getConstrucao() instanceof Entidades.Habitat)
                            {
                                if(((Entidades.Habitat)oMapaLocal.getConstrucao()).getoDragao()!=null)
                                {
                                    strTextoBotao+="<br />" + ((Entidades.Habitat)oMapaLocal.getConstrucao()).getoDragao().getNomeDragao();
                                }
                            }
                            
                            oButtonMapaLocal.setText(strTextoBotao);
                        }
                        else
                        {
                            oButtonMapaLocal.setText("");
                        }
                    }
                 }
             }
        }
    }
    
    private void CarregarEventosBotoes()
    {
        for(java.awt.Component oComponent : jPanelBotoes.getComponents())
        {
            javax.swing.JButton oButtonMapaLocal =(javax.swing.JButton)oComponent;
            
            oButtonMapaLocal.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    try {
                        BotaoClicado(((javax.swing.JButton)evt.getSource()).getName());
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao clicar no botão. Descrição: "+ ex.getMessage());
                    }
                }
            });
            
         }
    }
    
    private void BotaoClicado(String strNomeBotao) throws Exception
    {
        int x=Integer.parseInt(strNomeBotao.replace(STR_BOTAO, "").substring(0,1));
        int y=Integer.parseInt(strNomeBotao.replace(STR_BOTAO, "").substring(2,3));
        
        Entidades.MapaLocal oMapaLocal= oMapaRegrasNegocio.getMapaLocalPorPosicao(oJogoAtivo.getMapa(), x, y);
        
        if(oMapaLocal.getConstrucao()==null)
        {
            if(JOptionPane.showConfirmDialog(rootPane, "Não existe construções aqui. Deseja Construir?")==JOptionPane.YES_OPTION)
            {
                String strEntrada="";
                String strMensagem="O Que deseja Construir?\n1 - Fazenda - Ouro Requerido: %s\n2- Habitat\n0 - Sair";
                strMensagem=String.format(strMensagem, new Entidades.Fazenda().getValor());
                while(!IsConstrucaoValida(strEntrada))
                {   
                    strEntrada=JOptionPane.showInputDialog(strMensagem);
                    
                }
                switch(Integer.parseInt(strEntrada))
                {
                    case 1:
                        ConstruirFazenda(oMapaLocal);
                        break;
                    case 2:
                        ConstruirHabitat(oMapaLocal);
                        break;
                }
            }
        }
        else
        {
            if(oMapaLocal.getConstrucao() instanceof Entidades.CasaCentral)
            {
                CasaCentralClicada(oMapaLocal);
            }
            if(oMapaLocal.getConstrucao() instanceof Entidades.Habitat)
            {
                HabitatClicado(oMapaLocal);
            }
            if(oMapaLocal.getConstrucao() instanceof Entidades.Fazenda)
            {
                FazendaClicada();
            }
        }
    }
    private void CasaCentralClicada(Entidades.MapaLocal oMapaLocal) throws Exception
    {
        Entidades.CasaCentral oCasaCentral=((Entidades.CasaCentral)oMapaLocal.getConstrucao());
        
        if(oCasaCentral.getOvo()==null)
        {
            if(JOptionPane.showConfirmDialog(rootPane, "Não existe Ovo de Dragão aqui. Deseja criar um?")==JOptionPane.YES_OPTION)
            {
                String strDragaoTipoOpcao="";
                Entidades.DragaoTipo oDragaoTipo=null;
                String strDragoesDescricoes=oDragaoRegrasNegocio.getDragoesTipoDescricoes();
        
                while(oDragaoTipo==null)
                {
                    while(!Utils.Util.IsNumeric(strDragaoTipoOpcao))
                    {   
                        strDragaoTipoOpcao=JOptionPane.showInputDialog("Escolha um Tipo de Dragão: "+strDragoesDescricoes+ "\n0 - Sair");
                    }
                    if(Integer.parseInt(strDragaoTipoOpcao)==0) {
                        return;
                    }
                    oDragaoTipo= oDragaoRegrasNegocio.getDragaoTipoPorId(Integer.parseInt(strDragaoTipoOpcao));
                    if(oDragaoTipo!=null)
                    {
                        Entidades.Dragao oDragao=new Entidades.Dragao();
                        oDragao.setDragaoTipo(oDragaoTipo);
                        
                        //Validação
                        if(oDragaoTipo.getLevelJogadorRequerido()>oNivelRegrasNegocio.getNivelEquivalente(oJogoAtivo.getQtdTotalPontosXP()).getCodigo())
                        {
                            JOptionPane.showMessageDialog(rootPane, "Você não possui level para adquirir esse Dragão!");
                            oDragaoTipo=null;
                            strDragaoTipoOpcao="";
                        }
                        else if(oDragaoTipo.getValor()>oJogoAtivo.getVlrTotalOuro())
                        {
                            JOptionPane.showMessageDialog(rootPane, "Você não possui Ouro suficiente para adquirir esse Dragão!");
                            oDragaoTipo=null;
                            strDragaoTipoOpcao="";
                        }
                        else
                        {
                            String strNomeDragao="";
                            while(strNomeDragao==null || strNomeDragao.trim().length()==0)
                            {   
                                strNomeDragao=JOptionPane.showInputDialog("Dê um nome ao seu dragão:");
                            }
                            oJogoAtivo.setVlrTotalOuro(oJogoAtivo.getVlrTotalOuro()-oDragaoTipo.getValor());
                            oDragao.setNomeDragao(strNomeDragao);
                            oCasaCentral.setOvo(oDragao);
                            
                            oJogoAtivo.setQtdTotalPontosXP(oJogoAtivo.getQtdTotalPontosXP()+oDragao.getDragaoTipo().getPontosXPFornece());
                            JOptionPane.showMessageDialog(rootPane, "Você ganhou " +oDragao.getDragaoTipo().getPontosXPFornece() +" pontos de XP!");
            
                            GravarJogo();
                            CarregarItensTela();
                        }
                    }
                }
            }
        }
        else
        {
            String strSaida="Já existe um Ovo de " + oCasaCentral.getOvo().getDragaoTipo().getNomeTipoDragao() +" aqui. O Nome dele é: " +oCasaCentral.getOvo().getNomeDragao()+".";
            strSaida+="\nClique em um habitat do tipo " +oCasaCentral.getOvo().getDragaoTipo().getoHabitatTipo().getTipo() +" para criar o dragão.";
            
            JOptionPane.showMessageDialog(rootPane,strSaida);
        }
    }
    
    private void HabitatClicado(Entidades.MapaLocal oMapaLocal) throws Exception
    {
        Entidades.Habitat oHabitat=((Entidades.Habitat)oMapaLocal.getConstrucao());
        //Se tiver dragão pode apenas colher o ouro.
        //Para simplificar eu fiz um jeito de pegar o ouro direto, basta clicar no dragão.
        //Não vou adicionar lógica aqui, apenas para simplificar, porque esse sistema já está ficando grande demais ^^
        if(oHabitat.getoDragao()==null)
        {
            Entidades.CasaCentral oCasaCentral=oMapaRegrasNegocio.RetornarCasaCentralPorMapa(oJogoAtivo.getMapa());
            if(oCasaCentral.getOvo()==null)
            {
                JOptionPane.showMessageDialog(rootPane, "Habitat sem dragão. Para alocar um dragão aqui é necessário criar um Ovo na Casa Central.");
                return;
            }
            //Meu Deus, que negócio du mal! \o/ haha - Não acho isso muito bonito não. Mas é perfeitamente legivel. Só ficou com uma cara ruim porque são métodos e não atributos assim como no .NET
            if(oCasaCentral.getOvo().getDragaoTipo().getNomeTipoDragao().equals(oHabitat.getHabitatTipo().getoDragaoTipo().getNomeTipoDragao()))
            {
                if(JOptionPane.showConfirmDialog(rootPane,String.format("Deseja colocar o Dragão %s aqui?",oCasaCentral.getOvo().getNomeDragao()))==JOptionPane.YES_OPTION)
                {
                    oHabitat.setoDragao(oCasaCentral.getOvo());
                    oCasaCentral.setOvo(null);
                    
                    //Fiz uma regra de negócio para dar 50 pontos de XP ao colocar o Dragão em um habitat. 
                    oJogoAtivo.setQtdTotalPontosXP(oJogoAtivo.getQtdTotalPontosXP()+50);
                    JOptionPane.showMessageDialog(rootPane, "Parabéns! Você ganhou 50 pontos de XP!");
                            
                    GravarJogo();
                    CarregarItensTela();
                }
            }
        }
        else
        {
            oJogoAtivo.setVlrTotalOuro(oJogoAtivo.getVlrTotalOuro()+oHabitat.getoDragao().getDragaoTipo().getOuroFornece());
            //Regra de negócio - toda vez que colher ouro, também dá 10 de XP.
            oJogoAtivo.setQtdTotalPontosXP(oJogoAtivo.getQtdTotalPontosXP()+10);
            
            String strMensagem="Você ganhou " + oHabitat.getoDragao().getDragaoTipo().getOuroFornece() + " de ouro!\nE 10 pontos de XP.\nAgora o seu dragão está no level "+oHabitat.getoDragao().getLevel()+" .\nDeseja também alimentar o dragão?";
            
            if(JOptionPane.showConfirmDialog(rootPane, strMensagem) ==JOptionPane.YES_OPTION)
            {
                String strQuantidadeParaAlimentar="";
                while(!Utils.Util.IsNumeric(strQuantidadeParaAlimentar))
                {   
                    strQuantidadeParaAlimentar=JOptionPane.showInputDialog("Digite a quantidade de alimento ou \n0 - Para sair.");
                }
                if(Integer.parseInt(strQuantidadeParaAlimentar)<=0) {
                    return;
                }
                if(oJogoAtivo.getVlrTotalComida()<Integer.parseInt(strQuantidadeParaAlimentar))
                {
                    JOptionPane.showMessageDialog(rootPane, "A quantidade que você possui de frutas é insuficiente!");
                    return;
                }
                //A principio eu criei uma regra de negócio enorme para arcar com a experiência e o level do Dragão.
                //Porém para simplificar o jogo, a regra ficou:
                //Cada fruta alimentada, gera 1 de XP. Sendo que 100 de XP passa-se 1 level.
                oHabitat.getoDragao().setTotalExperiencia(oHabitat.getoDragao().getTotalExperiencia()+Integer.parseInt(strQuantidadeParaAlimentar));
                oJogoAtivo.setVlrTotalComida(oJogoAtivo.getVlrTotalComida()-Integer.parseInt(strQuantidadeParaAlimentar));
            }
            GravarJogo();
            CarregarItensTela();
        }
    }
    
    private void FazendaClicada() throws Exception
    {
        Entidades.Fruta oFruta=new Entidades.Fruta();
        
        oJogoAtivo.setVlrTotalComida(oJogoAtivo.getVlrTotalComida()+oFruta.getQuantidadeAlimento());
        //Regra de negócio - toda vez que colher fruta, também dá 10 de XP.
        oJogoAtivo.setQtdTotalPontosXP(oJogoAtivo.getQtdTotalPontosXP()+10);
        JOptionPane.showMessageDialog(rootPane, "Você ganhou " + oFruta.getQuantidadeAlimento() + " de frutas!\nE 10 pontos de XP.");
        
        GravarJogo();
        CarregarItensTela();
                
    }
    
    private void ConstruirFazenda(Entidades.MapaLocal oMapaLocal) throws Exception
    {
        Fazenda oFazenda=new Fazenda();
        
        if(oFazenda.getValor()>oJogoAtivo.getVlrTotalOuro())
        {
            JOptionPane.showMessageDialog(rootPane, "Você não possui Ouro suficiente para adquirir essa fazenda!");
        }
        else
        {
            oJogoAtivo.setVlrTotalOuro(oJogoAtivo.getVlrTotalOuro()-oFazenda.getValor());
            oJogoAtivo.setQtdTotalPontosXP(oJogoAtivo.getQtdTotalPontosXP()+oFazenda.getPontosXP());
            
            oMapaLocal.setConstrucao(new Fazenda());
            JOptionPane.showMessageDialog(rootPane, "Você ganhou " +oFazenda.getPontosXP() +" pontos de XP!");
            GravarJogo();
            CarregarItensTela();
        }
    }
    
    private void ConstruirHabitat(Entidades.MapaLocal oMapaLocal) throws Exception
    {
        String strHabitatTipoOpcao="";
        Entidades.HabitatTipo oHabitatTipo=null;
        String strHabitatDescricoes=oHabitatRegrasNegocio.getHabitatDescricoes();
        
        while(oHabitatTipo==null)
        {
            while(!Utils.Util.IsNumeric(strHabitatTipoOpcao))
            {   
                strHabitatTipoOpcao=JOptionPane.showInputDialog("Escolha um Tipo de Habitat: "+strHabitatDescricoes+ "\n0 - Sair");
            }
            if(Integer.parseInt(strHabitatTipoOpcao)==0) {
                return;
            }
            oHabitatTipo= oHabitatRegrasNegocio.getHabitatTipoPorId(Integer.parseInt(strHabitatTipoOpcao));
            if(oHabitatTipo!=null)
            {
                Entidades.Habitat oHabitat=new Entidades.Habitat();
                oHabitat.setHabitatTipo(oHabitatTipo);
                if(oHabitatTipo.getoDragaoTipo().getLevelJogadorRequerido()>oNivelRegrasNegocio.getNivelEquivalente(oJogoAtivo.getQtdTotalPontosXP()).getCodigo())
                {
                    JOptionPane.showMessageDialog(rootPane, "Você não possui level para adquirir esse habitat.");
                    oHabitatTipo=null;
                    strHabitatTipoOpcao="";
                }
                else if(oHabitatTipo.getValor()>oJogoAtivo.getVlrTotalOuro())
                {
                    JOptionPane.showMessageDialog(rootPane, "Você não possui Ouro suficiente para adquirir esse Habitat!");
                    oHabitatTipo=null;
                    strHabitatTipoOpcao="";
                }
                else
                {
                    oJogoAtivo.setVlrTotalOuro(oJogoAtivo.getVlrTotalOuro()-oHabitatTipo.getValor());
                    oJogoAtivo.setQtdTotalPontosXP(oJogoAtivo.getQtdTotalPontosXP()+oHabitatTipo.getPontosXPFornecido());
                    
                    JOptionPane.showMessageDialog(rootPane, "Você ganhou " +oHabitatTipo.getPontosXPFornecido() +" pontos de XP!");
            
                    oMapaLocal.setConstrucao(oHabitat);
                    GravarJogo();
                    CarregarItensTela();
                }
            }
        }
        
    }
    
    
    private boolean IsConstrucaoValida(String strEntrada)
    {
        if(!Utils.Util.IsNumeric(strEntrada)) {
            return false;
        }
        
        if(Integer.parseInt(strEntrada) >=0 && Integer.parseInt(strEntrada)<=2) {
            return true;
        }
        return false;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarJogo;
    private javax.swing.JButton btnMapaLocal1x1;
    private javax.swing.JButton btnMapaLocal1x2;
    private javax.swing.JButton btnMapaLocal1x3;
    private javax.swing.JButton btnMapaLocal1x4;
    private javax.swing.JButton btnMapaLocal1x5;
    private javax.swing.JButton btnMapaLocal1x6;
    private javax.swing.JButton btnMapaLocal2x1;
    private javax.swing.JButton btnMapaLocal2x2;
    private javax.swing.JButton btnMapaLocal2x3;
    private javax.swing.JButton btnMapaLocal2x4;
    private javax.swing.JButton btnMapaLocal2x5;
    private javax.swing.JButton btnMapaLocal2x6;
    private javax.swing.JButton btnMapaLocal3x1;
    private javax.swing.JButton btnMapaLocal3x2;
    private javax.swing.JButton btnMapaLocal3x3;
    private javax.swing.JButton btnMapaLocal3x4;
    private javax.swing.JButton btnMapaLocal3x5;
    private javax.swing.JButton btnMapaLocal3x6;
    private javax.swing.JButton btnMapaLocal4x1;
    private javax.swing.JButton btnMapaLocal4x2;
    private javax.swing.JButton btnMapaLocal4x3;
    private javax.swing.JButton btnMapaLocal4x4;
    private javax.swing.JButton btnMapaLocal4x5;
    private javax.swing.JButton btnMapaLocal4x6;
    private javax.swing.JButton btnMapaLocal5x1;
    private javax.swing.JButton btnMapaLocal5x2;
    private javax.swing.JButton btnMapaLocal5x3;
    private javax.swing.JButton btnMapaLocal5x4;
    private javax.swing.JButton btnMapaLocal5x5;
    private javax.swing.JButton btnMapaLocal5x6;
    private javax.swing.JButton btnSairJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JLabel lblDadosGerais;
    private javax.swing.JLabel lblMackDragonCity;
    // End of variables declaration//GEN-END:variables
}
